before_all do
    ensure_git_branch
    ensure_git_status_clean
    git pull
  end
  
  platform :ios do
    lane :create_app_id do
      produce(
        app_name: "Jays Sea Moss",
        app_identifier: "com.dhuntleypro.jaysseamoss",
        language: "English",
        skip_itc: true,
        skip_deploy: true
      )
    end
  
    private_lane :staging_build do
      app_store_version = get_app_store_version_number(bundle_id: 'ReactNativeFastlane')
      plist_version = get_version_number_from_plist(xcodeproj: './ios/ReactNativeFastlane.xcodeproj')
      
      if Gem::Version.new(plist_version.to_f) == Gem::Version.new(app_store_version.to_f)
        UI.message "Bumping minor version"
        increment_version_number_in_plist(
          xcodeproj: './ios/ReactNativeFastlane.xcodeproj',
          bump_type: 'minor'
        )
      else
        UI.message "Bumping patch version"
        increment_version_number_in_plist(
          xcodeproj: './ios/ReactNativeFastlane.xcodeproj',
          bump_type: 'patch'
        )
      end
  
      increment_build_number_in_plist(
        xcodeproj: './ios/ReactNativeFastlane.xcodeproj',
        target: 'ReactNativeFastlane'
      )
      gym(
        scheme: 'ReactNativeFastlane-staging',
        workspace: './ios/ReactNativeFastlane.xcworkspace'
      )
    end
  
    lane :beta do
      staging_build
      upload_to_testflight(
        username: 'dhuntleypro@icloud.com',
        app_identifier: 'com.yourcompany.yourapp'
      )
      commit_version_bump(message: 'Bump build number')
      push_to_git_remote
    end
  end
  